corvid/corvid/settings.py
corvid/corvid/urls.py
corvid/main/admin.py
corvid/main/migrations/0001_initial.py
corvid/main/models/category.py
corvid/main/models/page.py
corvid/main/models/page_plugin.py
corvid/main/models/post.py
corvid/main/models/project.py
corvid/main/models/project_plugin.py
corvid/main/models/tag.py
corvid/main/models/theme.py
corvid/main/models/user.py
corvid/main/templates/account_home.html
corvid/main/templates/base.html
corvid/main/templates/create_account.html
corvid/main/templates/create_project.html
corvid/main/templates/registration/logged_out.html
corvid/main/templates/registration/login.html
corvid/main/urls.py
corvid/main/views/home.py
corvid/main/views/login.py
corvid/main/views/root.py
corvid/main/views/user.py

So that we're not all working on the same branch

Models & Login Screen

---

corvid/main/templates/success.html
corvid/main/views/create_project.py
corvid/main/views/page.py
corvid/main/views/registration.py

Adds return links to registration/creation pages.

Return links

---

corvid/corvid/settings.py
corvid/main/views/create_project.py
corvid/main/views/page.py
corvid/main/views/project_home.py
corvid/main/views/protected_view.py
corvid/main/views/user.py

Addresses issue #11. Users should now be redirected to the login page upon viewing unauthorized content.

Move ProtectedViewMixin up to block unauthenticated users

---

corvid/main/tests/base.py
corvid/main/tests/test_root_view.py
corvid/main/tests/test_user_view.py

This PR has tests for `root_controller` and `UserHomeView`.  It identified issue #11, whose fix will have to be merged into this branch before the PR is accepted.

Demo1 tests

---

Makefile

It's nice to check your test coverage as you write tests, so I made this.

Add coverage rule to makefile.

---

corvid/main/migrations/0003_post_project.py
corvid/main/models/category.py
corvid/main/models/post.py
corvid/main/templates/edit_category.html
corvid/main/templates/project_home.html
corvid/main/urls.py
corvid/main/views/category.py
corvid/main/views/post.py
corvid/main/views/project_home.py

- Create Category controller (with link on project home)
+ no delete option, but this controller should be temporary
- Create / Update Post controllers (with links on project home)

View enchancements

---

corvid/main/forms/registration.py
corvid/main/tests/test_page_views.py
corvid/main/tests/test_project_home_view.py
corvid/main/tests/test_registration_view.py
corvid/main/views/project_home.py

I'm working on upping unit test coverage here.  Not ready for merge yet.

Construct additional tests

---

corvid/main/migrations/0004_auto_20151112_2025.py
corvid/main/migrations/0005_auto_20151112_2034.py
corvid/main/migrations/0006_auto_20151112_2035.py
corvid/main/migrations/0007_auto_20151112_2037.py
corvid/main/migrations/0008_auto_20151112_2038.py
corvid/main/migrations/0009_auto_20151112_2039.py
corvid/main/migrations/0010_auto_20151112_2040.py
corvid/main/migrations/0011_auto_20151112_2040.py
corvid/main/models/category.py
corvid/main/models/page.py
corvid/main/models/page_plugin.py
corvid/main/models/post.py
corvid/main/models/project.py
corvid/main/models/project_plugin.py
corvid/main/models/tag.py
corvid/main/models/theme.py
corvid/main/views/page.py

Enforced uniqueness on "primary key" fields in all models. Added indexes for good measure. Resolves issue #34.
@brenns10

Model uniqueness

---

corvid/main/management/commands/tswizzle.py
requirements.txt

Run `python manage.py tswizzle` to create:
- user `taytay`, password `taytay`
- a project under that user title `TSwizzle`
- an about page for this website
- A post containing the song lyrics, for each song she released on an album.
- Categories for each of her albums.
This is partially because I like Taylor Swift, and partially because I already had tho tools to put together something like this, which makes great filler data to test site generation on large projects.

Add a management command to populate the database with a TSwizzle site.

---

corvid/main/templates/error.html
corvid/main/urls.py
corvid/main/views/registration.py
corvid/main/views/unauthenticated.py

Resolves #20 
It's cute, and has Javascript redirect, and I did it using a decorator and mixin, just like the ProtectedViewMixin.  And somehow, it broke zero tests.  ¯\\\_(ツ)_/¯

Implement a 'you derped' message for login and registration.

---

corvid/main/templates/registration/login.html

Add a nifty jumbotron to the login page.

---

corvid/main/static/corvid.css
corvid/main/templates/project_home.html

Made the project home page a little prettier

---

corvid/corvid/settings.py
corvid/main/static/corvid.css
corvid/main/templates/base.html
corvid/main/views/page.py
corvid/main/views/post.py
requirements.txt

Posts and pages now have Pagedown, which is StackOverflow's markdown editor, sanitizer, and previewer.  Everything is done client side.  It's mostly transparent, except I had to add some custom forms.
On the topic of custom forms, I didn't put them in the `main.forms` package.  They were each like 4 lines, and it just didn't seam right to create two files for two 4 line classes.  Shoot me down if I overstepped.

Markdown editor

---

corvid/main/views/post.py

Resolves #53. Before, we were just grabbing all categories in the database. Hwoops :)

Make CrUd Post not grab categories from other projects

---

corvid/main/templates/project_home.html
corvid/main/tests/test_page_views.py
corvid/main/tests/test_post_views.py
corvid/main/urls.py
corvid/main/views/page.py
corvid/main/views/post.py

Reference by id instead of title for pages and posts

---

corvid/main/migrations/0014_auto_20151130_1200.py
corvid/main/migrations/0015_auto_20151130_1202.py
corvid/main/models/page.py
corvid/main/models/post.py
corvid/main/tests/test_models.py
corvid/main/views/site_generation.py

Duplicate page post names

---

corvid/main/static/corvid.css
corvid/main/templates/edit_page_post.html

Move the cancel/submit buttons on page/post views to top.

---

corvid/corvid/settings.py
corvid/main/tests/test_category_view.py
corvid/main/views/category.py

Added automatic session timeout

---

corvid/main/static/corvid.css
corvid/main/templates/edit_category.html
corvid/main/templates/project_home.html
corvid/main/tests/test_category_view.py
corvid/main/urls.py
corvid/main/views/__init__.py
corvid/main/views/category.py

Make category tag a link to edit category name

---

corvid/main/static/corvid.css
corvid/main/templates/edit_category.html
corvid/main/templates/project_home.html
corvid/main/tests/test_category_view.py
corvid/main/urls.py
corvid/main/views/__init__.py
corvid/main/views/category.py

Add the ability to edit the title of a category

---

corvid/main/forms/create_project.py
corvid/main/tests/test_project_view.py

Validate that project titles have no forward slash.

---

corvid/main/forms/clone_project.py
corvid/main/forms/create_project.py
corvid/main/migrations/0017_auto_20151202_2212.py
corvid/main/models/project.py
corvid/main/tests/test_project_view.py

Adding the validation to username is a bit weird.

Added validation to Project.title and User.username

---

corvid/main/models/post.py
corvid/main/tests/test_cloning.py

Resolves #92 
I went full itertools on the cloning tests, so I feel pretty good about that :)

Fix bug in cloning when a Post has no Category.

---

corvid/main/forms/__init__.py
corvid/main/forms/page.py
corvid/main/forms/post.py
corvid/main/migrations/0017_auto_20151202_1513.py
corvid/main/migrations/0018_merge.py
corvid/main/models/page_plugin.py
corvid/main/models/project.py
corvid/main/templates/project_home.html
corvid/main/tests/test_page_plugin_view.py
corvid/main/urls.py
corvid/main/views/__init__.py
corvid/main/views/page.py
corvid/main/views/page_plugins.py
corvid/main/views/post.py
corvid/main/views/project_home.py
corvid/main/views/site_generation.py
themes/bootstrap/templates/article.html
themes/bootstrap/templates/page.html
themes/default/templates/article.html
themes/default/templates/page.html
themes/html5-dopetrope/templates/article.html
themes/html5-dopetrope/templates/page.html

I am going to try this fix now. Didn't add my commit :cry:
Fix:
* Rebased on master
* merged migrations

Page plugins fix

---

corvid/main/forms/page.py
corvid/main/forms/post.py

This would've bugged the crap out of me.

Rename PostPlugins -> PagePlugins in edit Page/Post form
